version: "2"

services:
  dev:
    image: pawzar/devops:php-fpm
    network_mode: host
    volumes:
      - .:/website
    working_dir: /website/publisher/demo
    user: dev
    entrypoint: ['yarn']
    command: ['develop']
